import { Inter } from "next/font/google";
import {NextUIProvider} from "@nextui-org/react";
import "./globals.css";

import MainNavbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <NextUIProvider>
          <MainNavbar />
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
